# Generated by Django 4.2 on 2023-05-27 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('rank', models.CharField(choices=[('Consultant', 'Consultant'), ('Specialist', 'Specialist'), ('Senior Registrar', 'Senior Registrar'), ('Registrar', 'Registrar')], max_length=20)),
                ('specialty', models.CharField(choices=[('IMC', 'IMC'), ('Surgery', 'Surgery'), ('OBG', 'OBG'), ('Pedia', 'Pedia'), ('Ortho', 'Ortho'), ('Nepherology', 'Nepherology')], max_length=20)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
